sudo: false
language: ruby
cache: bundler
before_install: "gem install bundler"
rvm:
  - 2.4.1
  - 2.3.1
  - 2.2.5
  - 2.1
  - 2.0
  - 1.9.3
  - jruby-19mode
gemfile:
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_0.gemfile
matrix:
  exclude:
    - rvm: 2.1
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 2.0
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_4_1.gemfile
script: "bundle exec rake test"
