language: ruby
cache: bundler
before_install:
  - "gem update --system"
  - "gem install bundler"
rvm:
  - 2.7.0
  - 2.6.5
  - 2.5.7
  - 2.4.9
  - 2.3.8
  - jruby-9.2.8.0
gemfile:
  - gemfiles/rails_6_0.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_5_1.gemfile
matrix:
  exclude:
    - rvm: 2.3.8
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: 2.4.9
      gemfile: gemfiles/rails_6_0.gemfile
script: "bundle exec rake test"
