name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - '3.3'
          - '3.2'
          - '3.1'
          - '3.0'
        rails-version:
          - '7.2'
          - '7.1'
          - '7.0'
          - '6.1'

        include:
          - ruby-version: '3.1'
            rails-version: '6.0'

          - ruby-version: '3.0'
            rails-version: '6.0'

          - ruby-version: '2.7'
            rails-version: '7.1'
          - ruby-version: '2.7'
            rails-version: '7.0'
          - ruby-version: '2.7'
            rails-version: '6.1'
          - ruby-version: '2.7'
            rails-version: '6.0'
          - ruby-version: '2.7'
            rails-version: '5.2'
          - ruby-version: '2.7'
            rails-version: '5.1'

          - ruby-version: '2.6'
            rails-version: '6.1'
          - ruby-version: '2.6'
            rails-version: '6.0'
          - ruby-version: '2.6'
            rails-version: '5.2'
          - ruby-version: '2.6'
            rails-version: '5.1'

          - ruby-version: jruby
            rails-version: '6.1'

        exclude:
          - ruby-version: '3.0'
            rails-version: '7.2'

    env:
      RUBY_VERSION: ${{ matrix.ruby-version }}
      RAILS_VERSION: ${{ matrix.rails-version }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
    # uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: bundle exec rake
